{"name": "test_login_with_retries_and_forgot", "status": "passed", "start": 1748415583852, "stop": 1748415623386, "uuid": "71fdfe30-cb42-46ea-a51f-1601b37f4fee", "historyId": "92d455666683493d2f68c46b98d31bde", "testCaseId": "92d455666683493d2f68c46b98d31bde", "fullName": "login.login#test_login_with_retries_and_forgot", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "story", "value": "Three invalid attempts, then valid login, then forgot password"}, {"name": "parentSuite", "value": "login"}, {"name": "suite", "value": "login"}, {"name": "host", "value": "ruban"}, {"name": "thread", "value": "49913-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login.login"}]}